spring:
  application:
    name: photoapp-config-server
  profiles:
    active: native # git for using Git as backend
  cloud:
    config:
      server:
        git:
          # uri: # Git repository URI
          # username:
          # password:
          clone-on-start: true
        native:
          searchLocations: 'file:///C:/Users/jporto/Projects/Courses/Spring Boot Microservices and Spring Cloud/local-config'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8012

management:
  endpoints:
    web:
      exposure.include: bus-refresh

encrypt:
  # symmetric encryption
  # key: mZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9y$B&E)H@McQfTjWnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B
  # asymmetric encryption
  key-store:
    type: jks
    location: 'file:///C:/Users/jporto/Projects/Courses/Spring Boot Microservices and Spring Cloud/PhotoAppApiConfigServer/PKI/server.jks'
    alias: apiEncryptionKey
    password: photoapp
    secret: changeme