server:
  port: ${PORT:0}

spring:
  application:
    name: users-ws
  datasource:
    # url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: photoapp_dbuser
    password: photoapp_dbuser
  jpa:
    hibernate:
      ddl-auto: update # if a table does not exist, it will be created
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    sender.type: web # rabbitmq, kafka
  sleuth:
    enabled: true
    sampler.probability: 1.0 # 1 for 100 % traceability information sent to Zipkin
  devtools:
    restart.enabled: true

logging:
  file:
    name: users-ws.log
  level:
    root: INFO
    '[me.learning.microservices.photoapp.api.users.data.AlbumsServiceClient]': DEBUG

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure.include: mappings,routes,beans

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka

gateway:
  ip: 127.0.0.1

feign:
  hystrix:
    enabled: true

authorization:
  token:
    secret: fdd1202ef90decd8376dca9bdd2747ed77b417eb7ddc0995184aa3cd7a15fc1b
    expiration-time: 864000000
    header:
      name: Authorization
      prefix: Bearer

login:
  url.path: /users/login

myapplication.environment: DEVELOPMENT

