server:
  error:
    include-message: always

spring:
  couchbase:
    connection-string: couchbase://localhost
    user-name: photoapp_dbuser
    password: '{cipher}AQB+sqkxoVlKzKEfW2OB6PhM6F21GOWn23iZnZUTORe43hn5WaMYNY900Zog1wSe2BmLwDcREteYIeB4O3yMb3e87llg0Ukq033yRQQRhQWxQS5Mlm7zGvnSA7nV6HV2EhZ7FXH5I+n/+TnNhdg8MccDZz0BiSyj2eEAVeFdwE3fSbPqtxWztEyF6NujbQiAhYPny8ivFyzhfvio1Y+xLE9eqXkCJwvdNbpb3iCKTR/1U2JoWlQWGZKcXo77cnGFvzngxT4GhCEBxqDSm6shuNvlwmrJ444CdWX84nnf62pVjnHzIhO/2TkXRcD4LbEuT6CP6Mb502cwak5tPcs+HB8DNr3CgEW10JeS7vmKbDNvqiG0XJrFfIYSg8DJPMWOADY='
    bucket-name: albums
    auto-index-creation: true