gateway:
  ip: 127.0.0.1

authorization:
  token:
    expiration-time: 864000000
    secret: '{cipher}AQAPv1nmwFcyodpT0Hcy9DArkfCZ1RwkRt11Id+WKc95E0i0Vz610081ZjvkUhiT/8WOXzCX7+hQB4DY7fnl8aZ4hOuw8vTKWY3ZUOXzAVh3VgMEuj1qKLylJ66xNu2VKN4aShEMCtuq5itjtP7RAfY6nZy8kp5cdUxFzEzb1UC+++/MHRdpbiQmRdHJgGbp14fWfni9zXSv1tKujMZ+UVE9mRPtjUwtDywE5J5nAxWsEgfKC1lYcvuY8uGTJFewNGigxlyl+G/kScbAhufM3en2uzuWM6e4PeN0VHQlQ61yKm7c3baz6ixVOhx7YbcYGiLGoPZtY169U4L0cYsBkHfBFaZr8ERYow0APYpnLZ9TuYcGtzeXXLwSpTBfHxlAZ4tCEEJAkEin7TMPK2NPpfM+sqZSvTNgrk9/3MCxBHIKRyZ54/6E26bmI6sc2FJgJJz0vG6KCtY1/Wm8k/97I5Pm'
    header:
      name: Authorization
      prefix: Bearer

eureka:
  client:
    password: '{cipher}AQBbe8O0mBk8sRrlKtGqAWUZr6F+W+ZotHA1dgCZxsHhSQZ3CIqmSyUvVMajSA3CdjXoXhDYRMcNzoRUX6w7yf/Grds8b5vLLj7RxsR17QyqHmmSSID0D+h4E7D3jNYkzsebn2cllT/4IML8iieZ7Bfwq9xFe2IVLgyghSXFJ84FWeRTZXReI8eRnr2O/9el+EhhFIBymV8Dw3MeiIZCMzMSYM/PE5zXMDD8D5Yjr3rDxHvveDW2z1HLaCj0oDA/3r6ms1qVnUKZNA0HmC+ogmwLl0taFHoE4HJETT5R19CJAAIb+Xh4wt2Joaqx+/a0vw1TpXwpwvpHP39udZq33b0MtS4rIrOJ98mYemEI0clRNe7y0YCrZqZohZlw5Hh0Y6I='
    serviceUrl.defaultZone: http://eureka:${eureka.client.password}@localhost:8010/eureka