spring:
  security:
    user:
      name: '{cipher}AQBbe8O0mBk8sRrlKtGqAWUZr6F+W+ZotHA1dgCZxsHhSQZ3CIqmSyUvVMajSA3CdjXoXhDYRMcNzoRUX6w7yf/Grds8b5vLLj7RxsR17QyqHmmSSID0D+h4E7D3jNYkzsebn2cllT/4IML8iieZ7Bfwq9xFe2IVLgyghSXFJ84FWeRTZXReI8eRnr2O/9el+EhhFIBymV8Dw3MeiIZCMzMSYM/PE5zXMDD8D5Yjr3rDxHvveDW2z1HLaCj0oDA/3r6ms1qVnUKZNA0HmC+ogmwLl0taFHoE4HJETT5R19CJAAIb+Xh4wt2Joaqx+/a0vw1TpXwpwvpHP39udZq33b0MtS4rIrOJ98mYemEI0clRNe7y0YCrZqZohZlw5Hh0Y6I='
      password: '{cipher}AQBbe8O0mBk8sRrlKtGqAWUZr6F+W+ZotHA1dgCZxsHhSQZ3CIqmSyUvVMajSA3CdjXoXhDYRMcNzoRUX6w7yf/Grds8b5vLLj7RxsR17QyqHmmSSID0D+h4E7D3jNYkzsebn2cllT/4IML8iieZ7Bfwq9xFe2IVLgyghSXFJ84FWeRTZXReI8eRnr2O/9el+EhhFIBymV8Dw3MeiIZCMzMSYM/PE5zXMDD8D5Yjr3rDxHvveDW2z1HLaCj0oDA/3r6ms1qVnUKZNA0HmC+ogmwLl0taFHoE4HJETT5R19CJAAIb+Xh4wt2Joaqx+/a0vw1TpXwpwvpHP39udZq33b0MtS4rIrOJ98mYemEI0clRNe7y0YCrZqZohZlw5Hh0Y6I='

eureka:
  server:
    enableSelfPreservation: false