server:
  port: ${PORT:0}
  error:
    include-message: always

spring:
  application:
    name: albums-ws
  couchbase:
    connection-string: couchbase://localhost
    user-name: photoapp_dbuser
    password: photoapp_dbuser
    bucket-name: albums
    auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    sender.type: web # rabbitmq, kafka
  sleuth:
    enabled: true
    sampler.probability: 1.0 # 1 for 100 % traceability information sent to Zipkin
  devtools:
    restart.enabled: true

logging:
  file:
    name: albums-ws.log
  level:
    root: INFO
    '[me.learning.microservices.photoapp.api.albums.data.UsersServiceClient]': DEBUG

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure.include: mappings,routes,beans

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka

gateway:
  ip: 127.0.0.1

feign:
  hystrix:
    enabled: true

authorization:
  token:
    secret: fdd1202ef90decd8376dca9bdd2747ed77b417eb7ddc0995184aa3cd7a15fc1b
    expiration-time: 864000000
    header:
      name: Authorization
      prefix: Bearer