spring:
  application:
    name: albums-ws
  couchbase:
    connection-string: couchbase://localhost
    user-name: photoapp_dbuser
    password: photoapp_dbuser
    bucket-name: albums
    auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    enabled: false
  sleuth:
    enabled: false

logging:
  file:
    name: albums-ws.log
  level:
    root: INFO
    '[me.learning.microservices.photoapp.api.albums.data.UsersServiceClient]': DEBUG

management:
  trace:
    http:
      enabled: false
  endpoints:
    web:
      exposure.include:

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka

feign:
  hystrix:
    enabled: true

authorization:
  token:
    secret: fdd1202ef90decd8376dca9bdd2747ed77b417eb7ddc0995184aa3cd7a15fc1b
    expiration-time: 864000000
    header:
      name: Authorization
      prefix: Bearer