spring:
  config:
    import: 'optional:configserver:http://localhost:8012'
  cloud:
    config:
      enabled: true
      uri: http://localhost:8012
      retry:
        max-interval: 3000
        maxAttempts: 6
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: # override it for production
  devtools:
    restart.enabled: false

eureka:
  instance:
    hostname: # override it or set at startup
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka

authorization:
  token:
    secret: # set at startup by environment or config server
    expiration-time: 86400000
