server:
  port: ${PORT:0}

spring:
  application:
    name: account-management-ws
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  devtools:
    restart.enabled: true

logging:
  file:
    name: account-management-ws.log

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka
