server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-ws-auth
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/**
            - Method=GET,POST,PUT,DELETE
            - Header=Authorization, Bearer (.+)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: users-ws-no-auth
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users, /users-ws/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - id: albums-ws-auth
          uri: lb://albums-ws
          predicates:
            - Path=/albums-ws/**
            - Method=GET,POST,PUT,DELETE
            - Header=Authorization, Bearer (.+)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/albums-ws/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
      # discovery:
       # locator:
         # enabled: true
         # lower-case-service-id: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka

management:
  trace:
    http:
      # default repositories implementations are in-memory and may consume too many resources
      # to enable HTTP tracing, contribute a bean implementing HttpTraceRepository or AuditEventRepository
      enabled: true
  endpoint.gateway:
    enabled: true
  endpoints:
    web:
      exposure.include: beans,health,routes,httptrace,gateway

api:
  h2console:
    url.path: /users-ws/h2-console
  signup:
    url.path: /users-ws/users
  login:
    url.path: /users-ws/users/login
  api-gateway:
    actuator:
      url.path: /actuator/*
  users:
    actuator:
      url.path: /users-ws/actuator/*

authorization:
  token:
    secret: fdd1202ef90decd8376dca9bdd2747ed77b417eb7ddc0995184aa3cd7a15fc1b
    header:
      prefix: Bearer