server:
  port: 8010

spring:
  # config: # comment out to enable external configuration
    # import: 'optional:configserver:http://localhost:8012'
  cloud:
    config:
      enabled: false
      uri: http://localhost:8012
      name: discovery-service
      fail-fast: true
      retry:
        max-interval: 3000
        maxAttempts: 6
    bus:
      enabled: false
  application:
    name: discovery-service
  security:
    user:
      name: eureka
      password: eureka

eureka:
  instance:
    prefer-ip-address: false
  server:
    enableSelfPreservation: false