server:
  port: 8010

spring:
  application:
    name: discovery-service

eureka:
  instance:
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://localhost:8010/eureka