# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build PhotoApp back-end artifacts with Maven

on:
  push:
    branches: [ master, github-actions-ci-cd ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Config Server
      run: mvn -B package --file PhotoAppApiConfigServer/pom.xml
    - name: Build Discovery Service
      run: mvn -B package --file PhotoAppDiscoveryService/pom.xml
    - name: Build Account Management microservice
      run: mvn -B package --file PhotoAppApiAccountManagement/pom.xml
    - name: Build Users microservice
      run: mvn -B package --file PhotoAppApiUsers/pom.xml
    - name: Build Albums microservice
      run: mvn -B package --file PhotoAppApiAlbums/pom.xml
    - name: Build API Gateway
      run: mvn -B package --file PhotoAppApiGateway/pom.xml
